In [1]:
import pandas as pd

In [2]:
brands = pd.read_csv("../data/raw_data/brands.csv")
categories = pd.read_csv("../data/raw_data/categories.csv")
customers = pd.read_csv("../data/raw_data/customers.csv")
orders = pd.read_csv("../data/raw_data/orders.csv")
order_items = pd.read_csv("../data/raw_data/order_items.csv")
products = pd.read_csv("../data/raw_data/products.csv")
staffs = pd.read_csv("../data/raw_data/staffs.csv")
stocks = pd.read_csv("../data/raw_data/stocks.csv")
stores = pd.read_csv("../data/raw_data/stores.csv")

In [4]:
customers.head()

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code
0,1,Debra,Burks,NaN,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127
1,2,Kasha,Todd,NaN,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008
2,3,Tameka,Fisher,NaN,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278
3,4,Daryl,Spence,NaN,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820

In [5]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  1445 non-null   int64
 1   first_name   1445 non-null   str
 2   last_name    1445 non-null   str
 3   phone        178 non-null    str
 4   email        1445 non-null   str
 5   street       1445 non-null   str
 6   city         1445 non-null   str
 7   state        1445 non-null   str
 8   zip_code     1445 non-null   int64
dtypes: int64(2), str(7)
memory usage: 101.7 KB

In [6]:
customers.isnull().sum()

customer_id       0
first_name        0
last_name         0
phone          1267
email             0
street            0
city              0
state             0
zip_code          0
dtype: int64

In [7]:
customers.duplicated().sum()

np.int64(0)

In [9]:
orders.head()

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6

In [10]:
orders.info()
orders.isnull().sum()
orders.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1615 entries, 0 to 1614
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1615 non-null   int64
 1   customer_id    1615 non-null   int64
 2   order_status   1615 non-null   int64
 3   order_date     1615 non-null   str
 4   required_date  1615 non-null   str
 5   shipped_date   1445 non-null   str
 6   store_id       1615 non-null   int64
 7   staff_id       1615 non-null   int64
dtypes: int64(5), str(3)
memory usage: 101.1 KB

np.int64(0)

In [11]:
order_items.head()

   order_id  item_id  product_id  quantity  list_price  discount
0         1        1          20         1      599.99      0.20
1         1        2           8         2     1799.99      0.07
2         1        3          10         2     1549.00      0.05
3         1        4          16         2      599.99      0.05
4         1        5           4         1     2899.99      0.20

In [12]:
order_items.info()
order_items.isnull().sum()
order_items.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 4722 entries, 0 to 4721
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    4722 non-null   int64
 1   item_id     4722 non-null   int64
 2   product_id  4722 non-null   int64
 3   quantity    4722 non-null   int64
 4   list_price  4722 non-null   float64
 5   discount    4722 non-null   float64
dtypes: float64(2), int64(4)
memory usage: 221.5 KB

np.int64(0)

In [13]:
products.head()

,product_id,product_name,brand_id,category_id,model_year,list_price
0,1,Trek 820 - 2016,9,6,2016,379.99
1,2,Ritchey Timberwolf Frameset - 2016,5,6,2016,749.99
2,3,Surly Wednesday Frameset - 2016,8,6,2016,999.99
3,4,Trek Fuel EX 8 29 - 2016,9,6,2016,2899.99
4,5,Heller Shagamaw Frame - 2016,3,6,2016,1320.99

In [14]:
products.info()
products.isnull().sum()
products.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 321 entries, 0 to 320
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    321 non-null    int64
 1   product_name  321 non-null    str
 2   brand_id      321 non-null    int64
 3   category_id   321 non-null    int64
 4   model_year    321 non-null    int64
 5   list_price    321 non-null    float64
dtypes: float64(1), int64(4), str(1)
memory usage: 15.2 KB

np.int64(0)

In [15]:
staffs.head()

,staff_id,first_name,last_name,email,phone,active,store_id,manager_id
0,1,Fabiola,Jackson,fabiola.jackson@bikes.shop,(831) 555-5554,1,1,NaN
1,2,Mireya,Copeland,mireya.copeland@bikes.shop,(831) 555-5555,1,1,1.0
2,3,Genna,Serrano,genna.serrano@bikes.shop,(831) 555-5556,1,1,2.0
3,4,Virgie,Wiggins,virgie.wiggins@bikes.shop,(831) 555-5557,1,1,2.0
4,5,Jannette,David,jannette.david@bikes.shop,(516) 379-4444,1,2,1.0

In [16]:
staffs.info()
staffs.isnull().sum()
staffs.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   staff_id    10 non-null     int64
 1   first_name  10 non-null     str
 2   last_name   10 non-null     str
 3   email       10 non-null     str
 4   phone       10 non-null     str
 5   active      10 non-null     int64
 6   store_id    10 non-null     int64
 7   manager_id  9 non-null      float64
dtypes: float64(1), int64(3), str(4)
memory usage: 772.0 bytes

np.int64(0)

In [17]:
stores.head()

,store_id,store_name,phone,email,street,city,state,zip_code
0,1,Santa Cruz Bikes,(831) 476-4321,santacruz@bikes.shop,3700 Portola Drive,Santa Cruz,CA,95060
1,2,Baldwin Bikes,(516) 379-8888,baldwin@bikes.shop,4200 Chestnut Lane,Baldwin,NY,11432
2,3,Rowlett Bikes,(972) 530-5555,rowlett@bikes.shop,8000 Fairway Avenue,Rowlett,TX,75088

In [18]:
stores.info()
stores.isnull().sum()
stores.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    3 non-null      int64
 1   store_name  3 non-null      str
 2   phone       3 non-null      str
 3   email       3 non-null      str
 4   street      3 non-null      str
 5   city        3 non-null      str
 6   state       3 non-null      str
 7   zip_code    3 non-null      int64
dtypes: int64(2), str(6)
memory usage: 324.0 bytes

np.int64(0)

In [19]:
stocks.head()

   store_id  product_id  quantity
0         1           1        27
1         1           2         5
2         1           3         6
3         1           4        23
4         1           5        22

In [20]:
stocks.info()
stocks.isnull().sum()
stocks.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    939 non-null    int64
 1   product_id  939 non-null    int64
 2   quantity    939 non-null    int64
dtypes: int64(3)
memory usage: 22.1 KB

np.int64(0)

In [21]:
brands.head()

   brand_id   brand_name
0         1      Electra
1         2         Haro
2         3       Heller
3         4  Pure Cycles
4         5      Ritchey

In [22]:
brands.info()
brands.isnull().sum()
brands.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   brand_id    9 non-null      int64
 1   brand_name  9 non-null      str
dtypes: int64(1), str(1)
memory usage: 276.0 bytes

np.int64(0)

In [23]:
categories.head()

   category_id        category_name
0            1    Children Bicycles
1            2     Comfort Bicycles
2            3    Cruisers Bicycles
3            4  Cyclocross Bicycles
4            5       Electric Bikes

In [24]:
categories.info()
categories.isnull().sum()
categories.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   category_id    7 non-null      int64
 1   category_name  7 non-null      str
dtypes: int64(1), str(1)
memory usage: 244.0 bytes

np.int64(0)

In [25]:
# Dataset Audit Phase completed -------------------->

In [27]:
orders.isnull().sum()

order_id           0
customer_id        0
order_status       0
order_date         0
required_date      0
shipped_date     170
store_id           0
staff_id           0
dtype: int64

In [28]:
orders["order_date"] = pd.to_datetime(orders["order_date"])
orders["required_date"] = pd.to_datetime(orders["required_date"])
orders["shipped_date"] = pd.to_datetime(orders["shipped_date"])

In [29]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 1615 entries, 0 to 1614
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1615 non-null   int64
 1   customer_id    1615 non-null   int64
 2   order_status   1615 non-null   int64
 3   order_date     1615 non-null   datetime64[us]
 4   required_date  1615 non-null   datetime64[us]
 5   shipped_date   1445 non-null   datetime64[us]
 6   store_id       1615 non-null   int64
 7   staff_id       1615 non-null   int64
dtypes: datetime64[us](3), int64(5)
memory usage: 101.1 KB

In [30]:
orders[orders["shipped_date"].isnull()]

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
69,70,50,3,2016-02-11,2016-02-11,NaT,3,9
75,76,9,3,2016-02-16,2016-02-16,NaT,2,6
157,158,117,3,2016-04-04,2016-04-04,NaT,3,9
184,185,24,3,2016-04-20,2016-04-20,NaT,1,2
238,239,13,3,2016-05-27,2016-05-27,NaT,3,9
...,...,...,...,...,...,...,...,...
1610,1611,6,3,2018-09-06,2018-09-06,NaT,2,7
1611,1612,3,3,2018-10-21,2018-10-21,NaT,1,3
1612,1613,1,3,2018-11-18,2018-11-18,NaT,2,6
1613,1614,135,3,2018-11-28,2018-11-28,NaT,3,8
1614,1615,136,3,2018-12-28,2018-12-28,NaT,3,8

In [31]:
products.describe()

       product_id    brand_id  category_id   model_year    list_price
count  321.000000  321.000000   321.000000   321.000000    321.000000
mean   161.000000    5.476636     4.028037  2017.591900   1520.591402
std     92.808944    3.708131     2.188569     0.665063   1612.152765
min      1.000000    1.000000     1.000000  2016.000000     89.990000
25%     81.000000    1.000000     2.000000  2017.000000    439.990000
50%    161.000000    7.000000     3.000000  2018.000000    761.990000
75%    241.000000    9.000000     6.000000  2018.000000   2299.990000
max    321.000000    9.000000     7.000000  2019.000000  11999.990000

In [32]:
customers_clean = customers.copy()
orders_clean = orders.copy()
products_clean = products.copy()

In [33]:
customers_clean.to_csv("../data/processed_data/customers_clean.csv", index=False)

orders_clean.to_csv("../data/processed_data/orders_clean.csv", index=False)

products_clean.to_csv("../data/processed_data/products_clean.csv", index=False)